### PR TITLE
small bugfix: now the script can also produce the output files when it is run on the Mac/Linux machine!

### PR DESCRIPTION
**Pull request by haowuintub**

### CODE REVIEW

**Comment by balacmi** [comment]
Thanks. Can you pleasecalso add a line in the README under Development that this has been changed?

**Comment by haowuintub** [comment]
> 

Do you mean something like this? :

v4.1.3
fixed the Bug regarding running the script "RunCalculateUAMTravelTimes.java" on Mac/Linux

**Comment by balacmi** [comment]
Something like this:

Development
- fixed the Bug regarding running the script "RunCalculateUAMTravelTimes.java" on Mac/Linux

V4.1.2
....

**Comment by haowuintub** [comment]
Dear Dr. Balac, sorry for closing this PR, because this is not a draft PR and I can not update the README here. So I created a new PR.

**Pull request closed without merging**
