### PR TITLE
The old matsim-uam-4.1.3-jar-with-dependencies.jar has some compiling…

### PR DESCRIPTION
**Pull request by haowuintub**
… issues? Somehow does not work. I uploaded here the correct one :)

When I use the old jar, here is the message:
Exception in thread "main" java.lang.NoClassDefFoundError: net/bhl/matsim/uam/scenario/RunCreateUAMBeelineScenario
	at org.eqasim.sao_paulo.scenario.CreateUAMScenario.main(CreateUAMScenario.java:9)
Caused by: java.lang.ClassNotFoundException: net.bhl.matsim.uam.scenario.RunCreateUAMBeelineScenario
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more

Process finished with exit code 1

### CODE REVIEW

**Comment by RRothfeld** [comment]
Hey Hao, thank you for noticing! Before merging however, I would like to ask: in your commit I can only see the updated .jar-File but no changes in code. Have any changes been necessary in the code as well or did you simply repackage using the existing code?

**Comment by balacmi** [comment]
This seems like something one does not want to do: provide a jar file within the project itself. We do have a repository where releases can be stored on packagecloud. Why is that one not used?

**Comment by haowuintub** [comment]
> Hey Hao, thank you for noticing! Before merging however, I would like to ask: in your commit I can only see the updated .jar-File but no changes in code. Have any changes been necessary in the code as well or did you simply repackage using the existing code?

Dear Raoul, Good morning. I simply repackage using the existing code of branch "routingBug" :)

**Comment by haowuintub** [comment]
> This seems like something one does not want to do: provide a jar file within the project itself. We do have a repository where releases can be stored on packagecloud. Why is that one not used?

Dear Milos,
Thanks for asking. It seems like we do not have a automatic pipeline on GitHub for generating the jar file like matsim-lib (When a verified version made, a jar will be generated automatically as P&R version, e.g., 16.0-PR3172). Currently, we do not have jar file with version 4.1.3. on ivt URL xwhere the jars are stored: [https://packagecloud.io/eth-ivt/uam](https://packagecloud.io/eth-ivt/uam)

**Comment by RRothfeld** [comment]
Hey Milos, hey Hao! I can't remember the state of the routing bug branch, but the master branch (which is ahead) should be used, shouldn't it? But I am also happy with Milos' idea that no jar files are stored within the code but only externally.

**Comment by balacmi** [comment]
I can make a new release, 4.1.3, and store it properly. I suggest removing the provided jar file from the project. This would mean that someone who wants to work with the develop version would need to make the jar themselves. Would that be ok?

**Comment by RRothfeld** [comment]
Yes, thank's alot, Milos!

**Comment by balacmi** [comment]
I have created a new release. Please reopen this if something does not work with the released jar.

**Comment by haowuintub** [comment]
> Hey Milos, hey Hao! I can't remember the state of the routing bug branch, but the master branch (which is ahead) should be used, shouldn't it? But I am also happy with Milos' idea that no jar files are stored within the code but only externally.

Dear Raoul: actually, We should not include the code changes after 4.1.3 was released, isn't it?

Dear Milos: Thanks a lot, that makes more sense. I have test it and it works now :)

**Pull request closed without merging**
